import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
// import NavBar from "./components/NavBar";

const josefin = Poppins({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Penskull Studios",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en" data-theme="light">
        <body className={`bg-[#281549] text-white ${josefin.className}`}>
          {/* <NavBar /> */}
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
